In [1]:
import dmrg2 as dmrg
import SpinSystems_2d as SS2d
import numpy as np

0 0
[[1. 0.]
 [0. 1.]]
0 1
[[0. 0.]
 [0. 0.]]
0 2
[[0. 0.]
 [0. 0.]]
0 3
[[0. 0.]
 [0. 0.]]
0 4
[[0. 0.]
 [0. 0.]]
0 5
[[0. 0.]
 [0. 0.]]
1 0
[[ 1.  0.]
 [ 0. -1.]]
1 1
[[0. 0.]
 [0. 0.]]
1 2
[[0. 0.]
 [0. 0.]]
1 3
[[0. 0.]
 [0. 0.]]
1 4
[[0. 0.]
 [0. 0.]]
1 5
[[0. 0.]
 [0. 0.]]
2 0
[[0. 0.]
 [0. 0.]]
2 1
[[1. 0.]
 [0. 1.]]
2 2
[[0. 0.]
 [0. 0.]]
2 3
[[0. 0.]
 [0. 0.]]
2 4
[[0. 0.]
 [0. 0.]]
2 5
[[0. 0.]
 [0. 0.]]
3 0
[[0. 0.]
 [0. 0.]]
3 1
[[0. 0.]
 [0. 0.]]
3 2
[[1. 0.]
 [0. 1.]]
3 3
[[0. 0.]
 [0. 0.]]
3 4
[[0. 0.]
 [0. 0.]]
3 5
[[0. 0.]
 [0. 0.]]
4 0
[[0. 0.]
 [0. 0.]]
4 1
[[0. 0.]
 [0. 0.]]
4 2
[[0. 0.]
 [0. 0.]]
4 3
[[1. 0.]
 [0. 1.]]
4 4
[[0. 0.]
 [0. 0.]]
4 5
[[0. 0.]
 [0. 0.]]
5 0
[[ 0. -1.]
 [-1.  0.]]
5 1
[[-0.5 -0. ]
 [-0.   0.5]]
5 2
[[0. 0.]
 [0. 0.]]
5 3
[[0. 0.]
 [0. 0.]]
5 4
[[-0.5 -0. ]
 [-0.   0.5]]
5 5
[[1. 0.]
 [0. 1.]]


In [2]:
Lx = 5
Ly = 5

L = Lx*Ly

In [ ]:
h_space = np.linspace(-3,3,64)
e = []
for h in h_space:
    print(h)
    H = SS2d.IsingMPO_2D(Lx,Ly,h,1)

    engine = dmrg.DMRG2(H)
    engine.initialize(16)

    for i in range(10):
        engine.dmrg_step(1e-9)
    e.append(engine.E/L)

-3.0


C:\Users\asant\Documents\GitHub\Tensor-Network\LanczosRoutines.py:38: RuntimeWarning: beta[0] ~= 0 encountered during Lanczos iteration.
  warnings.warn(


-2.9047619047619047
-2.8095238095238093
-2.7142857142857144
-2.619047619047619
-2.5238095238095237
-2.428571428571429
-2.3333333333333335
-2.238095238095238
-2.142857142857143
-2.0476190476190474
-1.9523809523809526
-1.8571428571428572
-1.7619047619047619
-1.6666666666666667
-1.5714285714285716


In [ ]:
import matplotlib.pyplot as plt

plt.plot(engine.MPS.compute_EntEntropy())

In [ ]:
import MPO_class as MPO
mz = [0 for x in range(Lx*Ly)]
for i in range(len(mz)):
    mz[i] = MPO.getLocalMzMPO(len(mz),i)

In [ ]:
sz_meas = [0 for x in range(len(mz))]

for i in range(len(sz_meas)):
    sz_meas[i] = mz[i].contractMPOMPS(engine.MPS)


In [ ]:
engine.MPS

In [ ]:
Lx*Ly

In [ ]:
plt.plot(h_space,e)
plt.plot(h_space,-np.abs(h_space))

In [ ]:
plt.plot(h_space[1:],np.diff(e)/np.diff(h_space))